/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as LearningManagementSystemRouteImport } from './routes/learning-management-system'
import { Route as AttendanceManagementSystemRouteImport } from './routes/attendance-management-system'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as LearningManagementSystemIndexRouteImport } from './routes/learning-management-system.index'
import { Route as AttendanceManagementSystemIndexRouteImport } from './routes/attendance-management-system.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as LearningManagementSystemVerifyRouteImport } from './routes/learning-management-system.verify'
import { Route as LearningManagementSystemStudentRouteImport } from './routes/learning-management-system.student'
import { Route as LearningManagementSystemSignupRouteImport } from './routes/learning-management-system.signup'
import { Route as LearningManagementSystemResetPasswordRouteImport } from './routes/learning-management-system.reset-password'
import { Route as LearningManagementSystemLoginRouteImport } from './routes/learning-management-system.login'
import { Route as LearningManagementSystemInstructorRouteImport } from './routes/learning-management-system.instructor'
import { Route as LearningManagementSystemForgotPasswordRouteImport } from './routes/learning-management-system.forgot-password'
import { Route as LearningManagementSystemCatalogRouteImport } from './routes/learning-management-system.catalog'
import { Route as LearningManagementSystemAdminRouteImport } from './routes/learning-management-system.admin'
import { Route as CommunitiesKeyRouteImport } from './routes/communities.$key'
import { Route as AttendanceManagementSystemLoginRouteImport } from './routes/attendance-management-system.login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as LearningManagementSystemStudentIndexRouteImport } from './routes/learning-management-system.student.index'
import { Route as LearningManagementSystemInstructorIndexRouteImport } from './routes/learning-management-system.instructor.index'
import { Route as LearningManagementSystemAdminIndexRouteImport } from './routes/learning-management-system.admin.index'
import { Route as LearningManagementSystemInstructorsIdRouteImport } from './routes/learning-management-system.instructors.$id'
import { Route as LearningManagementSystemCoursesIdRouteImport } from './routes/learning-management-system.courses.$id'
import { Route as LearningManagementSystemCertificateIdRouteImport } from './routes/learning-management-system.certificate.$id'
import { Route as LearningManagementSystemStudentQuizCourseIdRouteImport } from './routes/learning-management-system.student.quiz.$courseId'
import { Route as LearningManagementSystemStudentPlayerCourseIdRouteImport } from './routes/learning-management-system.student.player.$courseId'
import { Route as LearningManagementSystemInstructorCoursesIdRouteImport } from './routes/learning-management-system.instructor.courses.$id'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemRoute =
  LearningManagementSystemRouteImport.update({
    id: '/learning-management-system',
    path: '/learning-management-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const AttendanceManagementSystemRoute =
  AttendanceManagementSystemRouteImport.update({
    id: '/attendance-management-system',
    path: '/attendance-management-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemIndexRoute =
  LearningManagementSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const AttendanceManagementSystemIndexRoute =
  AttendanceManagementSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AttendanceManagementSystemRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemVerifyRoute =
  LearningManagementSystemVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemStudentRoute =
  LearningManagementSystemStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemSignupRoute =
  LearningManagementSystemSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemResetPasswordRoute =
  LearningManagementSystemResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemLoginRoute =
  LearningManagementSystemLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemInstructorRoute =
  LearningManagementSystemInstructorRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemForgotPasswordRoute =
  LearningManagementSystemForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemCatalogRoute =
  LearningManagementSystemCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemAdminRoute =
  LearningManagementSystemAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const CommunitiesKeyRoute = CommunitiesKeyRouteImport.update({
  id: '/communities/$key',
  path: '/communities/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceManagementSystemLoginRoute =
  AttendanceManagementSystemLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AttendanceManagementSystemRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemStudentIndexRoute =
  LearningManagementSystemStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemInstructorIndexRoute =
  LearningManagementSystemInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)
const LearningManagementSystemAdminIndexRoute =
  LearningManagementSystemAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemInstructorsIdRoute =
  LearningManagementSystemInstructorsIdRouteImport.update({
    id: '/instructors/$id',
    path: '/instructors/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemCoursesIdRoute =
  LearningManagementSystemCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemCertificateIdRoute =
  LearningManagementSystemCertificateIdRouteImport.update({
    id: '/certificate/$id',
    path: '/certificate/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemStudentQuizCourseIdRoute =
  LearningManagementSystemStudentQuizCourseIdRouteImport.update({
    id: '/quiz/$courseId',
    path: '/quiz/$courseId',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemStudentPlayerCourseIdRoute =
  LearningManagementSystemStudentPlayerCourseIdRouteImport.update({
    id: '/player/$courseId',
    path: '/player/$courseId',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemInstructorCoursesIdRoute =
  LearningManagementSystemInstructorCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance-management-system': typeof AttendanceManagementSystemRouteWithChildren
  '/learning-management-system': typeof LearningManagementSystemRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminRouteWithChildren
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorRouteWithChildren
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentRouteWithChildren
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/attendance-management-system/': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system/': typeof LearningManagementSystemIndexRoute
  '/news/': typeof NewsIndexRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/admin/': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor/': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student/': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/admin': typeof AdminIndexRoute
  '/attendance-management-system': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system': typeof LearningManagementSystemIndexRoute
  '/news': typeof NewsIndexRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance-management-system': typeof AttendanceManagementSystemRouteWithChildren
  '/learning-management-system': typeof LearningManagementSystemRouteWithChildren
  '/super-admin': typeof SuperAdminRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminRouteWithChildren
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorRouteWithChildren
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentRouteWithChildren
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/attendance-management-system/': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system/': typeof LearningManagementSystemIndexRoute
  '/news/': typeof NewsIndexRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/admin/': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor/': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student/': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attendance-management-system'
    | '/learning-management-system'
    | '/super-admin'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/learning-management-system/admin'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/instructor'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/student'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/admin/'
    | '/attendance-management-system/'
    | '/learning-management-system/'
    | '/news/'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/admin/'
    | '/learning-management-system/instructor/'
    | '/learning-management-system/student/'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/super-admin'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/admin'
    | '/attendance-management-system'
    | '/learning-management-system'
    | '/news'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/admin'
    | '/learning-management-system/instructor'
    | '/learning-management-system/student'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attendance-management-system'
    | '/learning-management-system'
    | '/super-admin'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/learning-management-system/admin'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/instructor'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/student'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/admin/'
    | '/attendance-management-system/'
    | '/learning-management-system/'
    | '/news/'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/admin/'
    | '/learning-management-system/instructor/'
    | '/learning-management-system/student/'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendanceManagementSystemRoute: typeof AttendanceManagementSystemRouteWithChildren
  LearningManagementSystemRoute: typeof LearningManagementSystemRouteWithChildren
  SuperAdminRoute: typeof SuperAdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunitiesKeyRoute: typeof CommunitiesKeyRoute
  NewsIdRoute: typeof NewsIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system': {
      id: '/learning-management-system'
      path: '/learning-management-system'
      fullPath: '/learning-management-system'
      preLoaderRoute: typeof LearningManagementSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management-system': {
      id: '/attendance-management-system'
      path: '/attendance-management-system'
      fullPath: '/attendance-management-system'
      preLoaderRoute: typeof AttendanceManagementSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/': {
      id: '/learning-management-system/'
      path: '/'
      fullPath: '/learning-management-system/'
      preLoaderRoute: typeof LearningManagementSystemIndexRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/attendance-management-system/': {
      id: '/attendance-management-system/'
      path: '/'
      fullPath: '/attendance-management-system/'
      preLoaderRoute: typeof AttendanceManagementSystemIndexRouteImport
      parentRoute: typeof AttendanceManagementSystemRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/verify': {
      id: '/learning-management-system/verify'
      path: '/verify'
      fullPath: '/learning-management-system/verify'
      preLoaderRoute: typeof LearningManagementSystemVerifyRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/student': {
      id: '/learning-management-system/student'
      path: '/student'
      fullPath: '/learning-management-system/student'
      preLoaderRoute: typeof LearningManagementSystemStudentRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/signup': {
      id: '/learning-management-system/signup'
      path: '/signup'
      fullPath: '/learning-management-system/signup'
      preLoaderRoute: typeof LearningManagementSystemSignupRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/reset-password': {
      id: '/learning-management-system/reset-password'
      path: '/reset-password'
      fullPath: '/learning-management-system/reset-password'
      preLoaderRoute: typeof LearningManagementSystemResetPasswordRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/login': {
      id: '/learning-management-system/login'
      path: '/login'
      fullPath: '/learning-management-system/login'
      preLoaderRoute: typeof LearningManagementSystemLoginRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/instructor': {
      id: '/learning-management-system/instructor'
      path: '/instructor'
      fullPath: '/learning-management-system/instructor'
      preLoaderRoute: typeof LearningManagementSystemInstructorRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/forgot-password': {
      id: '/learning-management-system/forgot-password'
      path: '/forgot-password'
      fullPath: '/learning-management-system/forgot-password'
      preLoaderRoute: typeof LearningManagementSystemForgotPasswordRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/catalog': {
      id: '/learning-management-system/catalog'
      path: '/catalog'
      fullPath: '/learning-management-system/catalog'
      preLoaderRoute: typeof LearningManagementSystemCatalogRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/admin': {
      id: '/learning-management-system/admin'
      path: '/admin'
      fullPath: '/learning-management-system/admin'
      preLoaderRoute: typeof LearningManagementSystemAdminRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/communities/$key': {
      id: '/communities/$key'
      path: '/communities/$key'
      fullPath: '/communities/$key'
      preLoaderRoute: typeof CommunitiesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management-system/login': {
      id: '/attendance-management-system/login'
      path: '/login'
      fullPath: '/attendance-management-system/login'
      preLoaderRoute: typeof AttendanceManagementSystemLoginRouteImport
      parentRoute: typeof AttendanceManagementSystemRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/student/': {
      id: '/learning-management-system/student/'
      path: '/'
      fullPath: '/learning-management-system/student/'
      preLoaderRoute: typeof LearningManagementSystemStudentIndexRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/instructor/': {
      id: '/learning-management-system/instructor/'
      path: '/'
      fullPath: '/learning-management-system/instructor/'
      preLoaderRoute: typeof LearningManagementSystemInstructorIndexRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
    '/learning-management-system/admin/': {
      id: '/learning-management-system/admin/'
      path: '/'
      fullPath: '/learning-management-system/admin/'
      preLoaderRoute: typeof LearningManagementSystemAdminIndexRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/instructors/$id': {
      id: '/learning-management-system/instructors/$id'
      path: '/instructors/$id'
      fullPath: '/learning-management-system/instructors/$id'
      preLoaderRoute: typeof LearningManagementSystemInstructorsIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/courses/$id': {
      id: '/learning-management-system/courses/$id'
      path: '/courses/$id'
      fullPath: '/learning-management-system/courses/$id'
      preLoaderRoute: typeof LearningManagementSystemCoursesIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/certificate/$id': {
      id: '/learning-management-system/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/learning-management-system/certificate/$id'
      preLoaderRoute: typeof LearningManagementSystemCertificateIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/student/quiz/$courseId': {
      id: '/learning-management-system/student/quiz/$courseId'
      path: '/quiz/$courseId'
      fullPath: '/learning-management-system/student/quiz/$courseId'
      preLoaderRoute: typeof LearningManagementSystemStudentQuizCourseIdRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/student/player/$courseId': {
      id: '/learning-management-system/student/player/$courseId'
      path: '/player/$courseId'
      fullPath: '/learning-management-system/student/player/$courseId'
      preLoaderRoute: typeof LearningManagementSystemStudentPlayerCourseIdRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/instructor/courses/$id': {
      id: '/learning-management-system/instructor/courses/$id'
      path: '/courses/$id'
      fullPath: '/learning-management-system/instructor/courses/$id'
      preLoaderRoute: typeof LearningManagementSystemInstructorCoursesIdRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
  }
}

interface AttendanceManagementSystemRouteChildren {
  AttendanceManagementSystemLoginRoute: typeof AttendanceManagementSystemLoginRoute
  AttendanceManagementSystemIndexRoute: typeof AttendanceManagementSystemIndexRoute
}

const AttendanceManagementSystemRouteChildren: AttendanceManagementSystemRouteChildren =
  {
    AttendanceManagementSystemLoginRoute: AttendanceManagementSystemLoginRoute,
    AttendanceManagementSystemIndexRoute: AttendanceManagementSystemIndexRoute,
  }

const AttendanceManagementSystemRouteWithChildren =
  AttendanceManagementSystemRoute._addFileChildren(
    AttendanceManagementSystemRouteChildren,
  )

interface LearningManagementSystemAdminRouteChildren {
  LearningManagementSystemAdminIndexRoute: typeof LearningManagementSystemAdminIndexRoute
}

const LearningManagementSystemAdminRouteChildren: LearningManagementSystemAdminRouteChildren =
  {
    LearningManagementSystemAdminIndexRoute:
      LearningManagementSystemAdminIndexRoute,
  }

const LearningManagementSystemAdminRouteWithChildren =
  LearningManagementSystemAdminRoute._addFileChildren(
    LearningManagementSystemAdminRouteChildren,
  )

interface LearningManagementSystemInstructorRouteChildren {
  LearningManagementSystemInstructorIndexRoute: typeof LearningManagementSystemInstructorIndexRoute
  LearningManagementSystemInstructorCoursesIdRoute: typeof LearningManagementSystemInstructorCoursesIdRoute
}

const LearningManagementSystemInstructorRouteChildren: LearningManagementSystemInstructorRouteChildren =
  {
    LearningManagementSystemInstructorIndexRoute:
      LearningManagementSystemInstructorIndexRoute,
    LearningManagementSystemInstructorCoursesIdRoute:
      LearningManagementSystemInstructorCoursesIdRoute,
  }

const LearningManagementSystemInstructorRouteWithChildren =
  LearningManagementSystemInstructorRoute._addFileChildren(
    LearningManagementSystemInstructorRouteChildren,
  )

interface LearningManagementSystemStudentRouteChildren {
  LearningManagementSystemStudentIndexRoute: typeof LearningManagementSystemStudentIndexRoute
  LearningManagementSystemStudentPlayerCourseIdRoute: typeof LearningManagementSystemStudentPlayerCourseIdRoute
  LearningManagementSystemStudentQuizCourseIdRoute: typeof LearningManagementSystemStudentQuizCourseIdRoute
}

const LearningManagementSystemStudentRouteChildren: LearningManagementSystemStudentRouteChildren =
  {
    LearningManagementSystemStudentIndexRoute:
      LearningManagementSystemStudentIndexRoute,
    LearningManagementSystemStudentPlayerCourseIdRoute:
      LearningManagementSystemStudentPlayerCourseIdRoute,
    LearningManagementSystemStudentQuizCourseIdRoute:
      LearningManagementSystemStudentQuizCourseIdRoute,
  }

const LearningManagementSystemStudentRouteWithChildren =
  LearningManagementSystemStudentRoute._addFileChildren(
    LearningManagementSystemStudentRouteChildren,
  )

interface LearningManagementSystemRouteChildren {
  LearningManagementSystemAdminRoute: typeof LearningManagementSystemAdminRouteWithChildren
  LearningManagementSystemCatalogRoute: typeof LearningManagementSystemCatalogRoute
  LearningManagementSystemForgotPasswordRoute: typeof LearningManagementSystemForgotPasswordRoute
  LearningManagementSystemInstructorRoute: typeof LearningManagementSystemInstructorRouteWithChildren
  LearningManagementSystemLoginRoute: typeof LearningManagementSystemLoginRoute
  LearningManagementSystemResetPasswordRoute: typeof LearningManagementSystemResetPasswordRoute
  LearningManagementSystemSignupRoute: typeof LearningManagementSystemSignupRoute
  LearningManagementSystemStudentRoute: typeof LearningManagementSystemStudentRouteWithChildren
  LearningManagementSystemVerifyRoute: typeof LearningManagementSystemVerifyRoute
  LearningManagementSystemIndexRoute: typeof LearningManagementSystemIndexRoute
  LearningManagementSystemCertificateIdRoute: typeof LearningManagementSystemCertificateIdRoute
  LearningManagementSystemCoursesIdRoute: typeof LearningManagementSystemCoursesIdRoute
  LearningManagementSystemInstructorsIdRoute: typeof LearningManagementSystemInstructorsIdRoute
}

const LearningManagementSystemRouteChildren: LearningManagementSystemRouteChildren =
  {
    LearningManagementSystemAdminRoute:
      LearningManagementSystemAdminRouteWithChildren,
    LearningManagementSystemCatalogRoute: LearningManagementSystemCatalogRoute,
    LearningManagementSystemForgotPasswordRoute:
      LearningManagementSystemForgotPasswordRoute,
    LearningManagementSystemInstructorRoute:
      LearningManagementSystemInstructorRouteWithChildren,
    LearningManagementSystemLoginRoute: LearningManagementSystemLoginRoute,
    LearningManagementSystemResetPasswordRoute:
      LearningManagementSystemResetPasswordRoute,
    LearningManagementSystemSignupRoute: LearningManagementSystemSignupRoute,
    LearningManagementSystemStudentRoute:
      LearningManagementSystemStudentRouteWithChildren,
    LearningManagementSystemVerifyRoute: LearningManagementSystemVerifyRoute,
    LearningManagementSystemIndexRoute: LearningManagementSystemIndexRoute,
    LearningManagementSystemCertificateIdRoute:
      LearningManagementSystemCertificateIdRoute,
    LearningManagementSystemCoursesIdRoute:
      LearningManagementSystemCoursesIdRoute,
    LearningManagementSystemInstructorsIdRoute:
      LearningManagementSystemInstructorsIdRoute,
  }

const LearningManagementSystemRouteWithChildren =
  LearningManagementSystemRoute._addFileChildren(
    LearningManagementSystemRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendanceManagementSystemRoute: AttendanceManagementSystemRouteWithChildren,
  LearningManagementSystemRoute: LearningManagementSystemRouteWithChildren,
  SuperAdminRoute: SuperAdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  CommunitiesKeyRoute: CommunitiesKeyRoute,
  NewsIdRoute: NewsIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
