/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RegistrationRouteImport } from './routes/registration'
import { Route as OneMillionInitiativeHomeRouteImport } from './routes/one-million-initiative-home'
import { Route as OneMillionInitiativeDonorsRouteImport } from './routes/one-million-initiative-donors'
import { Route as OneMillionInitiativeRouteImport } from './routes/one-million-initiative'
import { Route as LearningManagementSystemRouteImport } from './routes/learning-management-system'
import { Route as InitiativeSurveyRouteImport } from './routes/initiative-survey'
import { Route as EventSurveyRouteImport } from './routes/event-survey'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AttendanceManagementSystemRouteImport } from './routes/attendance-management-system'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as LearningManagementSystemIndexRouteImport } from './routes/learning-management-system.index'
import { Route as AttendanceManagementSystemIndexRouteImport } from './routes/attendance-management-system.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ResourcesAiToolsRouteImport } from './routes/resources.ai-tools'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as LearningManagementSystemVerifyRouteImport } from './routes/learning-management-system.verify'
import { Route as LearningManagementSystemTrainerApplyRouteImport } from './routes/learning-management-system.trainer-apply'
import { Route as LearningManagementSystemStudentRouteImport } from './routes/learning-management-system.student'
import { Route as LearningManagementSystemSignupRouteImport } from './routes/learning-management-system.signup'
import { Route as LearningManagementSystemResetPasswordRouteImport } from './routes/learning-management-system.reset-password'
import { Route as LearningManagementSystemLoginRouteImport } from './routes/learning-management-system.login'
import { Route as LearningManagementSystemInstructorRouteImport } from './routes/learning-management-system.instructor'
import { Route as LearningManagementSystemForgotPasswordRouteImport } from './routes/learning-management-system.forgot-password'
import { Route as LearningManagementSystemCatalogRouteImport } from './routes/learning-management-system.catalog'
import { Route as LearningManagementSystemAdminRouteImport } from './routes/learning-management-system.admin'
import { Route as InitiativeClaimRouteImport } from './routes/initiative.claim'
import { Route as CommunitiesKeyRouteImport } from './routes/communities.$key'
import { Route as AttendanceManagementSystemLoginRouteImport } from './routes/attendance-management-system.login'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminInitiativeSurveyRouteImport } from './routes/admin.initiative-survey'
import { Route as AdminInitiativeRouteImport } from './routes/admin.initiative'
import { Route as AdminEventSurveyRouteImport } from './routes/admin.event-survey'
import { Route as LearningManagementSystemStudentIndexRouteImport } from './routes/learning-management-system.student.index'
import { Route as LearningManagementSystemInstructorIndexRouteImport } from './routes/learning-management-system.instructor.index'
import { Route as LearningManagementSystemAdminIndexRouteImport } from './routes/learning-management-system.admin.index'
import { Route as LearningManagementSystemStudentRequestsRouteImport } from './routes/learning-management-system.student.requests'
import { Route as LearningManagementSystemInstructorsIdRouteImport } from './routes/learning-management-system.instructors.$id'
import { Route as LearningManagementSystemInstructorProfileRouteImport } from './routes/learning-management-system.instructor.profile'
import { Route as LearningManagementSystemCoursesIdRouteImport } from './routes/learning-management-system.courses.$id'
import { Route as LearningManagementSystemCertificateIdRouteImport } from './routes/learning-management-system.certificate.$id'
import { Route as LearningManagementSystemAdminUsersRouteImport } from './routes/learning-management-system.admin.users'
import { Route as LearningManagementSystemAdminTrainerApplicationsRouteImport } from './routes/learning-management-system.admin.trainer-applications'
import { Route as LearningManagementSystemAdminReviewsRouteImport } from './routes/learning-management-system.admin.reviews'
import { Route as LearningManagementSystemAdminEnrollmentRequestsRouteImport } from './routes/learning-management-system.admin.enrollment-requests'
import { Route as LearningManagementSystemAdminCouponsRouteImport } from './routes/learning-management-system.admin.coupons'
import { Route as LearningManagementSystemAdminAttendanceLinkRouteImport } from './routes/learning-management-system.admin.attendance-link'
import { Route as LearningManagementSystemAdminAnalyticsRouteImport } from './routes/learning-management-system.admin.analytics'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LearningManagementSystemStudentQuizCourseIdRouteImport } from './routes/learning-management-system.student.quiz.$courseId'
import { Route as LearningManagementSystemStudentPlayerCourseIdRouteImport } from './routes/learning-management-system.student.player.$courseId'
import { Route as LearningManagementSystemInstructorCoursesIdRouteImport } from './routes/learning-management-system.instructor.courses.$id'
import { Route as LearningManagementSystemInstructorAssignmentsCourseIdRouteImport } from './routes/learning-management-system.instructor.assignments.$courseId'

const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrationRoute = RegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => rootRouteImport,
} as any)
const OneMillionInitiativeHomeRoute =
  OneMillionInitiativeHomeRouteImport.update({
    id: '/one-million-initiative-home',
    path: '/one-million-initiative-home',
    getParentRoute: () => rootRouteImport,
  } as any)
const OneMillionInitiativeDonorsRoute =
  OneMillionInitiativeDonorsRouteImport.update({
    id: '/one-million-initiative-donors',
    path: '/one-million-initiative-donors',
    getParentRoute: () => rootRouteImport,
  } as any)
const OneMillionInitiativeRoute = OneMillionInitiativeRouteImport.update({
  id: '/one-million-initiative',
  path: '/one-million-initiative',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemRoute =
  LearningManagementSystemRouteImport.update({
    id: '/learning-management-system',
    path: '/learning-management-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const InitiativeSurveyRoute = InitiativeSurveyRouteImport.update({
  id: '/initiative-survey',
  path: '/initiative-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const EventSurveyRoute = EventSurveyRouteImport.update({
  id: '/event-survey',
  path: '/event-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceManagementSystemRoute =
  AttendanceManagementSystemRouteImport.update({
    id: '/attendance-management-system',
    path: '/attendance-management-system',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemIndexRoute =
  LearningManagementSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const AttendanceManagementSystemIndexRoute =
  AttendanceManagementSystemIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AttendanceManagementSystemRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesAiToolsRoute = ResourcesAiToolsRouteImport.update({
  id: '/resources/ai-tools',
  path: '/resources/ai-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemVerifyRoute =
  LearningManagementSystemVerifyRouteImport.update({
    id: '/verify',
    path: '/verify',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemTrainerApplyRoute =
  LearningManagementSystemTrainerApplyRouteImport.update({
    id: '/trainer-apply',
    path: '/trainer-apply',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemStudentRoute =
  LearningManagementSystemStudentRouteImport.update({
    id: '/student',
    path: '/student',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemSignupRoute =
  LearningManagementSystemSignupRouteImport.update({
    id: '/signup',
    path: '/signup',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemResetPasswordRoute =
  LearningManagementSystemResetPasswordRouteImport.update({
    id: '/reset-password',
    path: '/reset-password',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemLoginRoute =
  LearningManagementSystemLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemInstructorRoute =
  LearningManagementSystemInstructorRouteImport.update({
    id: '/instructor',
    path: '/instructor',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemForgotPasswordRoute =
  LearningManagementSystemForgotPasswordRouteImport.update({
    id: '/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemCatalogRoute =
  LearningManagementSystemCatalogRouteImport.update({
    id: '/catalog',
    path: '/catalog',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemAdminRoute =
  LearningManagementSystemAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const InitiativeClaimRoute = InitiativeClaimRouteImport.update({
  id: '/initiative/claim',
  path: '/initiative/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunitiesKeyRoute = CommunitiesKeyRouteImport.update({
  id: '/communities/$key',
  path: '/communities/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceManagementSystemLoginRoute =
  AttendanceManagementSystemLoginRouteImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => AttendanceManagementSystemRoute,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInitiativeSurveyRoute = AdminInitiativeSurveyRouteImport.update({
  id: '/admin/initiative-survey',
  path: '/admin/initiative-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInitiativeRoute = AdminInitiativeRouteImport.update({
  id: '/admin/initiative',
  path: '/admin/initiative',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventSurveyRoute = AdminEventSurveyRouteImport.update({
  id: '/admin/event-survey',
  path: '/admin/event-survey',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemStudentIndexRoute =
  LearningManagementSystemStudentIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemInstructorIndexRoute =
  LearningManagementSystemInstructorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)
const LearningManagementSystemAdminIndexRoute =
  LearningManagementSystemAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemStudentRequestsRoute =
  LearningManagementSystemStudentRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemInstructorsIdRoute =
  LearningManagementSystemInstructorsIdRouteImport.update({
    id: '/instructors/$id',
    path: '/instructors/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemInstructorProfileRoute =
  LearningManagementSystemInstructorProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)
const LearningManagementSystemCoursesIdRoute =
  LearningManagementSystemCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemCertificateIdRoute =
  LearningManagementSystemCertificateIdRouteImport.update({
    id: '/certificate/$id',
    path: '/certificate/$id',
    getParentRoute: () => LearningManagementSystemRoute,
  } as any)
const LearningManagementSystemAdminUsersRoute =
  LearningManagementSystemAdminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminTrainerApplicationsRoute =
  LearningManagementSystemAdminTrainerApplicationsRouteImport.update({
    id: '/trainer-applications',
    path: '/trainer-applications',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminReviewsRoute =
  LearningManagementSystemAdminReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminEnrollmentRequestsRoute =
  LearningManagementSystemAdminEnrollmentRequestsRouteImport.update({
    id: '/enrollment-requests',
    path: '/enrollment-requests',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminCouponsRoute =
  LearningManagementSystemAdminCouponsRouteImport.update({
    id: '/coupons',
    path: '/coupons',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminAttendanceLinkRoute =
  LearningManagementSystemAdminAttendanceLinkRouteImport.update({
    id: '/attendance-link',
    path: '/attendance-link',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LearningManagementSystemAdminAnalyticsRoute =
  LearningManagementSystemAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => LearningManagementSystemAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningManagementSystemStudentQuizCourseIdRoute =
  LearningManagementSystemStudentQuizCourseIdRouteImport.update({
    id: '/quiz/$courseId',
    path: '/quiz/$courseId',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemStudentPlayerCourseIdRoute =
  LearningManagementSystemStudentPlayerCourseIdRouteImport.update({
    id: '/player/$courseId',
    path: '/player/$courseId',
    getParentRoute: () => LearningManagementSystemStudentRoute,
  } as any)
const LearningManagementSystemInstructorCoursesIdRoute =
  LearningManagementSystemInstructorCoursesIdRouteImport.update({
    id: '/courses/$id',
    path: '/courses/$id',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)
const LearningManagementSystemInstructorAssignmentsCourseIdRoute =
  LearningManagementSystemInstructorAssignmentsCourseIdRouteImport.update({
    id: '/assignments/$courseId',
    path: '/assignments/$courseId',
    getParentRoute: () => LearningManagementSystemInstructorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance-management-system': typeof AttendanceManagementSystemRouteWithChildren
  '/contact': typeof ContactRoute
  '/event-survey': typeof EventSurveyRoute
  '/initiative-survey': typeof InitiativeSurveyRoute
  '/learning-management-system': typeof LearningManagementSystemRouteWithChildren
  '/one-million-initiative': typeof OneMillionInitiativeRoute
  '/one-million-initiative-donors': typeof OneMillionInitiativeDonorsRoute
  '/one-million-initiative-home': typeof OneMillionInitiativeHomeRoute
  '/registration': typeof RegistrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/event-survey': typeof AdminEventSurveyRoute
  '/admin/initiative': typeof AdminInitiativeRoute
  '/admin/initiative-survey': typeof AdminInitiativeSurveyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/initiative/claim': typeof InitiativeClaimRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminRouteWithChildren
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorRouteWithChildren
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentRouteWithChildren
  '/learning-management-system/trainer-apply': typeof LearningManagementSystemTrainerApplyRoute
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/resources/ai-tools': typeof ResourcesAiToolsRoute
  '/admin/': typeof AdminIndexRoute
  '/attendance-management-system/': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system/': typeof LearningManagementSystemIndexRoute
  '/news/': typeof NewsIndexRoute
  '/learning-management-system/admin/analytics': typeof LearningManagementSystemAdminAnalyticsRoute
  '/learning-management-system/admin/attendance-link': typeof LearningManagementSystemAdminAttendanceLinkRoute
  '/learning-management-system/admin/coupons': typeof LearningManagementSystemAdminCouponsRoute
  '/learning-management-system/admin/enrollment-requests': typeof LearningManagementSystemAdminEnrollmentRequestsRoute
  '/learning-management-system/admin/reviews': typeof LearningManagementSystemAdminReviewsRoute
  '/learning-management-system/admin/trainer-applications': typeof LearningManagementSystemAdminTrainerApplicationsRoute
  '/learning-management-system/admin/users': typeof LearningManagementSystemAdminUsersRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructor/profile': typeof LearningManagementSystemInstructorProfileRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/student/requests': typeof LearningManagementSystemStudentRequestsRoute
  '/learning-management-system/admin/': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor/': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student/': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/assignments/$courseId': typeof LearningManagementSystemInstructorAssignmentsCourseIdRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/event-survey': typeof EventSurveyRoute
  '/initiative-survey': typeof InitiativeSurveyRoute
  '/one-million-initiative': typeof OneMillionInitiativeRoute
  '/one-million-initiative-donors': typeof OneMillionInitiativeDonorsRoute
  '/one-million-initiative-home': typeof OneMillionInitiativeHomeRoute
  '/registration': typeof RegistrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/event-survey': typeof AdminEventSurveyRoute
  '/admin/initiative': typeof AdminInitiativeRoute
  '/admin/initiative-survey': typeof AdminInitiativeSurveyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/initiative/claim': typeof InitiativeClaimRoute
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/trainer-apply': typeof LearningManagementSystemTrainerApplyRoute
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/resources/ai-tools': typeof ResourcesAiToolsRoute
  '/admin': typeof AdminIndexRoute
  '/attendance-management-system': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system': typeof LearningManagementSystemIndexRoute
  '/news': typeof NewsIndexRoute
  '/learning-management-system/admin/analytics': typeof LearningManagementSystemAdminAnalyticsRoute
  '/learning-management-system/admin/attendance-link': typeof LearningManagementSystemAdminAttendanceLinkRoute
  '/learning-management-system/admin/coupons': typeof LearningManagementSystemAdminCouponsRoute
  '/learning-management-system/admin/enrollment-requests': typeof LearningManagementSystemAdminEnrollmentRequestsRoute
  '/learning-management-system/admin/reviews': typeof LearningManagementSystemAdminReviewsRoute
  '/learning-management-system/admin/trainer-applications': typeof LearningManagementSystemAdminTrainerApplicationsRoute
  '/learning-management-system/admin/users': typeof LearningManagementSystemAdminUsersRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructor/profile': typeof LearningManagementSystemInstructorProfileRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/student/requests': typeof LearningManagementSystemStudentRequestsRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/assignments/$courseId': typeof LearningManagementSystemInstructorAssignmentsCourseIdRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/attendance-management-system': typeof AttendanceManagementSystemRouteWithChildren
  '/contact': typeof ContactRoute
  '/event-survey': typeof EventSurveyRoute
  '/initiative-survey': typeof InitiativeSurveyRoute
  '/learning-management-system': typeof LearningManagementSystemRouteWithChildren
  '/one-million-initiative': typeof OneMillionInitiativeRoute
  '/one-million-initiative-donors': typeof OneMillionInitiativeDonorsRoute
  '/one-million-initiative-home': typeof OneMillionInitiativeHomeRoute
  '/registration': typeof RegistrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/super-admin': typeof SuperAdminRoute
  '/admin/event-survey': typeof AdminEventSurveyRoute
  '/admin/initiative': typeof AdminInitiativeRoute
  '/admin/initiative-survey': typeof AdminInitiativeSurveyRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/chat': typeof ApiChatRoute
  '/attendance-management-system/login': typeof AttendanceManagementSystemLoginRoute
  '/communities/$key': typeof CommunitiesKeyRoute
  '/initiative/claim': typeof InitiativeClaimRoute
  '/learning-management-system/admin': typeof LearningManagementSystemAdminRouteWithChildren
  '/learning-management-system/catalog': typeof LearningManagementSystemCatalogRoute
  '/learning-management-system/forgot-password': typeof LearningManagementSystemForgotPasswordRoute
  '/learning-management-system/instructor': typeof LearningManagementSystemInstructorRouteWithChildren
  '/learning-management-system/login': typeof LearningManagementSystemLoginRoute
  '/learning-management-system/reset-password': typeof LearningManagementSystemResetPasswordRoute
  '/learning-management-system/signup': typeof LearningManagementSystemSignupRoute
  '/learning-management-system/student': typeof LearningManagementSystemStudentRouteWithChildren
  '/learning-management-system/trainer-apply': typeof LearningManagementSystemTrainerApplyRoute
  '/learning-management-system/verify': typeof LearningManagementSystemVerifyRoute
  '/news/$id': typeof NewsIdRoute
  '/resources/ai-tools': typeof ResourcesAiToolsRoute
  '/admin/': typeof AdminIndexRoute
  '/attendance-management-system/': typeof AttendanceManagementSystemIndexRoute
  '/learning-management-system/': typeof LearningManagementSystemIndexRoute
  '/news/': typeof NewsIndexRoute
  '/learning-management-system/admin/analytics': typeof LearningManagementSystemAdminAnalyticsRoute
  '/learning-management-system/admin/attendance-link': typeof LearningManagementSystemAdminAttendanceLinkRoute
  '/learning-management-system/admin/coupons': typeof LearningManagementSystemAdminCouponsRoute
  '/learning-management-system/admin/enrollment-requests': typeof LearningManagementSystemAdminEnrollmentRequestsRoute
  '/learning-management-system/admin/reviews': typeof LearningManagementSystemAdminReviewsRoute
  '/learning-management-system/admin/trainer-applications': typeof LearningManagementSystemAdminTrainerApplicationsRoute
  '/learning-management-system/admin/users': typeof LearningManagementSystemAdminUsersRoute
  '/learning-management-system/certificate/$id': typeof LearningManagementSystemCertificateIdRoute
  '/learning-management-system/courses/$id': typeof LearningManagementSystemCoursesIdRoute
  '/learning-management-system/instructor/profile': typeof LearningManagementSystemInstructorProfileRoute
  '/learning-management-system/instructors/$id': typeof LearningManagementSystemInstructorsIdRoute
  '/learning-management-system/student/requests': typeof LearningManagementSystemStudentRequestsRoute
  '/learning-management-system/admin/': typeof LearningManagementSystemAdminIndexRoute
  '/learning-management-system/instructor/': typeof LearningManagementSystemInstructorIndexRoute
  '/learning-management-system/student/': typeof LearningManagementSystemStudentIndexRoute
  '/learning-management-system/instructor/assignments/$courseId': typeof LearningManagementSystemInstructorAssignmentsCourseIdRoute
  '/learning-management-system/instructor/courses/$id': typeof LearningManagementSystemInstructorCoursesIdRoute
  '/learning-management-system/student/player/$courseId': typeof LearningManagementSystemStudentPlayerCourseIdRoute
  '/learning-management-system/student/quiz/$courseId': typeof LearningManagementSystemStudentQuizCourseIdRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/attendance-management-system'
    | '/contact'
    | '/event-survey'
    | '/initiative-survey'
    | '/learning-management-system'
    | '/one-million-initiative'
    | '/one-million-initiative-donors'
    | '/one-million-initiative-home'
    | '/registration'
    | '/sitemap.xml'
    | '/super-admin'
    | '/admin/event-survey'
    | '/admin/initiative'
    | '/admin/initiative-survey'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/initiative/claim'
    | '/learning-management-system/admin'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/instructor'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/student'
    | '/learning-management-system/trainer-apply'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/resources/ai-tools'
    | '/admin/'
    | '/attendance-management-system/'
    | '/learning-management-system/'
    | '/news/'
    | '/learning-management-system/admin/analytics'
    | '/learning-management-system/admin/attendance-link'
    | '/learning-management-system/admin/coupons'
    | '/learning-management-system/admin/enrollment-requests'
    | '/learning-management-system/admin/reviews'
    | '/learning-management-system/admin/trainer-applications'
    | '/learning-management-system/admin/users'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructor/profile'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/student/requests'
    | '/learning-management-system/admin/'
    | '/learning-management-system/instructor/'
    | '/learning-management-system/student/'
    | '/learning-management-system/instructor/assignments/$courseId'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/event-survey'
    | '/initiative-survey'
    | '/one-million-initiative'
    | '/one-million-initiative-donors'
    | '/one-million-initiative-home'
    | '/registration'
    | '/sitemap.xml'
    | '/super-admin'
    | '/admin/event-survey'
    | '/admin/initiative'
    | '/admin/initiative-survey'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/initiative/claim'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/trainer-apply'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/resources/ai-tools'
    | '/admin'
    | '/attendance-management-system'
    | '/learning-management-system'
    | '/news'
    | '/learning-management-system/admin/analytics'
    | '/learning-management-system/admin/attendance-link'
    | '/learning-management-system/admin/coupons'
    | '/learning-management-system/admin/enrollment-requests'
    | '/learning-management-system/admin/reviews'
    | '/learning-management-system/admin/trainer-applications'
    | '/learning-management-system/admin/users'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructor/profile'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/student/requests'
    | '/learning-management-system/admin'
    | '/learning-management-system/instructor'
    | '/learning-management-system/student'
    | '/learning-management-system/instructor/assignments/$courseId'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/attendance-management-system'
    | '/contact'
    | '/event-survey'
    | '/initiative-survey'
    | '/learning-management-system'
    | '/one-million-initiative'
    | '/one-million-initiative-donors'
    | '/one-million-initiative-home'
    | '/registration'
    | '/sitemap.xml'
    | '/super-admin'
    | '/admin/event-survey'
    | '/admin/initiative'
    | '/admin/initiative-survey'
    | '/admin/login'
    | '/api/chat'
    | '/attendance-management-system/login'
    | '/communities/$key'
    | '/initiative/claim'
    | '/learning-management-system/admin'
    | '/learning-management-system/catalog'
    | '/learning-management-system/forgot-password'
    | '/learning-management-system/instructor'
    | '/learning-management-system/login'
    | '/learning-management-system/reset-password'
    | '/learning-management-system/signup'
    | '/learning-management-system/student'
    | '/learning-management-system/trainer-apply'
    | '/learning-management-system/verify'
    | '/news/$id'
    | '/resources/ai-tools'
    | '/admin/'
    | '/attendance-management-system/'
    | '/learning-management-system/'
    | '/news/'
    | '/learning-management-system/admin/analytics'
    | '/learning-management-system/admin/attendance-link'
    | '/learning-management-system/admin/coupons'
    | '/learning-management-system/admin/enrollment-requests'
    | '/learning-management-system/admin/reviews'
    | '/learning-management-system/admin/trainer-applications'
    | '/learning-management-system/admin/users'
    | '/learning-management-system/certificate/$id'
    | '/learning-management-system/courses/$id'
    | '/learning-management-system/instructor/profile'
    | '/learning-management-system/instructors/$id'
    | '/learning-management-system/student/requests'
    | '/learning-management-system/admin/'
    | '/learning-management-system/instructor/'
    | '/learning-management-system/student/'
    | '/learning-management-system/instructor/assignments/$courseId'
    | '/learning-management-system/instructor/courses/$id'
    | '/learning-management-system/student/player/$courseId'
    | '/learning-management-system/student/quiz/$courseId'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AttendanceManagementSystemRoute: typeof AttendanceManagementSystemRouteWithChildren
  ContactRoute: typeof ContactRoute
  EventSurveyRoute: typeof EventSurveyRoute
  InitiativeSurveyRoute: typeof InitiativeSurveyRoute
  LearningManagementSystemRoute: typeof LearningManagementSystemRouteWithChildren
  OneMillionInitiativeRoute: typeof OneMillionInitiativeRoute
  OneMillionInitiativeDonorsRoute: typeof OneMillionInitiativeDonorsRoute
  OneMillionInitiativeHomeRoute: typeof OneMillionInitiativeHomeRoute
  RegistrationRoute: typeof RegistrationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuperAdminRoute: typeof SuperAdminRoute
  AdminEventSurveyRoute: typeof AdminEventSurveyRoute
  AdminInitiativeRoute: typeof AdminInitiativeRoute
  AdminInitiativeSurveyRoute: typeof AdminInitiativeSurveyRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiChatRoute: typeof ApiChatRoute
  CommunitiesKeyRoute: typeof CommunitiesKeyRoute
  InitiativeClaimRoute: typeof InitiativeClaimRoute
  NewsIdRoute: typeof NewsIdRoute
  ResourcesAiToolsRoute: typeof ResourcesAiToolsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registration': {
      id: '/registration'
      path: '/registration'
      fullPath: '/registration'
      preLoaderRoute: typeof RegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-million-initiative-home': {
      id: '/one-million-initiative-home'
      path: '/one-million-initiative-home'
      fullPath: '/one-million-initiative-home'
      preLoaderRoute: typeof OneMillionInitiativeHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-million-initiative-donors': {
      id: '/one-million-initiative-donors'
      path: '/one-million-initiative-donors'
      fullPath: '/one-million-initiative-donors'
      preLoaderRoute: typeof OneMillionInitiativeDonorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-million-initiative': {
      id: '/one-million-initiative'
      path: '/one-million-initiative'
      fullPath: '/one-million-initiative'
      preLoaderRoute: typeof OneMillionInitiativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system': {
      id: '/learning-management-system'
      path: '/learning-management-system'
      fullPath: '/learning-management-system'
      preLoaderRoute: typeof LearningManagementSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiative-survey': {
      id: '/initiative-survey'
      path: '/initiative-survey'
      fullPath: '/initiative-survey'
      preLoaderRoute: typeof InitiativeSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event-survey': {
      id: '/event-survey'
      path: '/event-survey'
      fullPath: '/event-survey'
      preLoaderRoute: typeof EventSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management-system': {
      id: '/attendance-management-system'
      path: '/attendance-management-system'
      fullPath: '/attendance-management-system'
      preLoaderRoute: typeof AttendanceManagementSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/': {
      id: '/learning-management-system/'
      path: '/'
      fullPath: '/learning-management-system/'
      preLoaderRoute: typeof LearningManagementSystemIndexRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/attendance-management-system/': {
      id: '/attendance-management-system/'
      path: '/'
      fullPath: '/attendance-management-system/'
      preLoaderRoute: typeof AttendanceManagementSystemIndexRouteImport
      parentRoute: typeof AttendanceManagementSystemRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/ai-tools': {
      id: '/resources/ai-tools'
      path: '/resources/ai-tools'
      fullPath: '/resources/ai-tools'
      preLoaderRoute: typeof ResourcesAiToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/verify': {
      id: '/learning-management-system/verify'
      path: '/verify'
      fullPath: '/learning-management-system/verify'
      preLoaderRoute: typeof LearningManagementSystemVerifyRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/trainer-apply': {
      id: '/learning-management-system/trainer-apply'
      path: '/trainer-apply'
      fullPath: '/learning-management-system/trainer-apply'
      preLoaderRoute: typeof LearningManagementSystemTrainerApplyRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/student': {
      id: '/learning-management-system/student'
      path: '/student'
      fullPath: '/learning-management-system/student'
      preLoaderRoute: typeof LearningManagementSystemStudentRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/signup': {
      id: '/learning-management-system/signup'
      path: '/signup'
      fullPath: '/learning-management-system/signup'
      preLoaderRoute: typeof LearningManagementSystemSignupRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/reset-password': {
      id: '/learning-management-system/reset-password'
      path: '/reset-password'
      fullPath: '/learning-management-system/reset-password'
      preLoaderRoute: typeof LearningManagementSystemResetPasswordRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/login': {
      id: '/learning-management-system/login'
      path: '/login'
      fullPath: '/learning-management-system/login'
      preLoaderRoute: typeof LearningManagementSystemLoginRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/instructor': {
      id: '/learning-management-system/instructor'
      path: '/instructor'
      fullPath: '/learning-management-system/instructor'
      preLoaderRoute: typeof LearningManagementSystemInstructorRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/forgot-password': {
      id: '/learning-management-system/forgot-password'
      path: '/forgot-password'
      fullPath: '/learning-management-system/forgot-password'
      preLoaderRoute: typeof LearningManagementSystemForgotPasswordRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/catalog': {
      id: '/learning-management-system/catalog'
      path: '/catalog'
      fullPath: '/learning-management-system/catalog'
      preLoaderRoute: typeof LearningManagementSystemCatalogRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/admin': {
      id: '/learning-management-system/admin'
      path: '/admin'
      fullPath: '/learning-management-system/admin'
      preLoaderRoute: typeof LearningManagementSystemAdminRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/initiative/claim': {
      id: '/initiative/claim'
      path: '/initiative/claim'
      fullPath: '/initiative/claim'
      preLoaderRoute: typeof InitiativeClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communities/$key': {
      id: '/communities/$key'
      path: '/communities/$key'
      fullPath: '/communities/$key'
      preLoaderRoute: typeof CommunitiesKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management-system/login': {
      id: '/attendance-management-system/login'
      path: '/login'
      fullPath: '/attendance-management-system/login'
      preLoaderRoute: typeof AttendanceManagementSystemLoginRouteImport
      parentRoute: typeof AttendanceManagementSystemRoute
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/initiative-survey': {
      id: '/admin/initiative-survey'
      path: '/admin/initiative-survey'
      fullPath: '/admin/initiative-survey'
      preLoaderRoute: typeof AdminInitiativeSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/initiative': {
      id: '/admin/initiative'
      path: '/admin/initiative'
      fullPath: '/admin/initiative'
      preLoaderRoute: typeof AdminInitiativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/event-survey': {
      id: '/admin/event-survey'
      path: '/admin/event-survey'
      fullPath: '/admin/event-survey'
      preLoaderRoute: typeof AdminEventSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/student/': {
      id: '/learning-management-system/student/'
      path: '/'
      fullPath: '/learning-management-system/student/'
      preLoaderRoute: typeof LearningManagementSystemStudentIndexRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/instructor/': {
      id: '/learning-management-system/instructor/'
      path: '/'
      fullPath: '/learning-management-system/instructor/'
      preLoaderRoute: typeof LearningManagementSystemInstructorIndexRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
    '/learning-management-system/admin/': {
      id: '/learning-management-system/admin/'
      path: '/'
      fullPath: '/learning-management-system/admin/'
      preLoaderRoute: typeof LearningManagementSystemAdminIndexRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/student/requests': {
      id: '/learning-management-system/student/requests'
      path: '/requests'
      fullPath: '/learning-management-system/student/requests'
      preLoaderRoute: typeof LearningManagementSystemStudentRequestsRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/instructors/$id': {
      id: '/learning-management-system/instructors/$id'
      path: '/instructors/$id'
      fullPath: '/learning-management-system/instructors/$id'
      preLoaderRoute: typeof LearningManagementSystemInstructorsIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/instructor/profile': {
      id: '/learning-management-system/instructor/profile'
      path: '/profile'
      fullPath: '/learning-management-system/instructor/profile'
      preLoaderRoute: typeof LearningManagementSystemInstructorProfileRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
    '/learning-management-system/courses/$id': {
      id: '/learning-management-system/courses/$id'
      path: '/courses/$id'
      fullPath: '/learning-management-system/courses/$id'
      preLoaderRoute: typeof LearningManagementSystemCoursesIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/certificate/$id': {
      id: '/learning-management-system/certificate/$id'
      path: '/certificate/$id'
      fullPath: '/learning-management-system/certificate/$id'
      preLoaderRoute: typeof LearningManagementSystemCertificateIdRouteImport
      parentRoute: typeof LearningManagementSystemRoute
    }
    '/learning-management-system/admin/users': {
      id: '/learning-management-system/admin/users'
      path: '/users'
      fullPath: '/learning-management-system/admin/users'
      preLoaderRoute: typeof LearningManagementSystemAdminUsersRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/trainer-applications': {
      id: '/learning-management-system/admin/trainer-applications'
      path: '/trainer-applications'
      fullPath: '/learning-management-system/admin/trainer-applications'
      preLoaderRoute: typeof LearningManagementSystemAdminTrainerApplicationsRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/reviews': {
      id: '/learning-management-system/admin/reviews'
      path: '/reviews'
      fullPath: '/learning-management-system/admin/reviews'
      preLoaderRoute: typeof LearningManagementSystemAdminReviewsRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/enrollment-requests': {
      id: '/learning-management-system/admin/enrollment-requests'
      path: '/enrollment-requests'
      fullPath: '/learning-management-system/admin/enrollment-requests'
      preLoaderRoute: typeof LearningManagementSystemAdminEnrollmentRequestsRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/coupons': {
      id: '/learning-management-system/admin/coupons'
      path: '/coupons'
      fullPath: '/learning-management-system/admin/coupons'
      preLoaderRoute: typeof LearningManagementSystemAdminCouponsRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/attendance-link': {
      id: '/learning-management-system/admin/attendance-link'
      path: '/attendance-link'
      fullPath: '/learning-management-system/admin/attendance-link'
      preLoaderRoute: typeof LearningManagementSystemAdminAttendanceLinkRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/learning-management-system/admin/analytics': {
      id: '/learning-management-system/admin/analytics'
      path: '/analytics'
      fullPath: '/learning-management-system/admin/analytics'
      preLoaderRoute: typeof LearningManagementSystemAdminAnalyticsRouteImport
      parentRoute: typeof LearningManagementSystemAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-management-system/student/quiz/$courseId': {
      id: '/learning-management-system/student/quiz/$courseId'
      path: '/quiz/$courseId'
      fullPath: '/learning-management-system/student/quiz/$courseId'
      preLoaderRoute: typeof LearningManagementSystemStudentQuizCourseIdRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/student/player/$courseId': {
      id: '/learning-management-system/student/player/$courseId'
      path: '/player/$courseId'
      fullPath: '/learning-management-system/student/player/$courseId'
      preLoaderRoute: typeof LearningManagementSystemStudentPlayerCourseIdRouteImport
      parentRoute: typeof LearningManagementSystemStudentRoute
    }
    '/learning-management-system/instructor/courses/$id': {
      id: '/learning-management-system/instructor/courses/$id'
      path: '/courses/$id'
      fullPath: '/learning-management-system/instructor/courses/$id'
      preLoaderRoute: typeof LearningManagementSystemInstructorCoursesIdRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
    '/learning-management-system/instructor/assignments/$courseId': {
      id: '/learning-management-system/instructor/assignments/$courseId'
      path: '/assignments/$courseId'
      fullPath: '/learning-management-system/instructor/assignments/$courseId'
      preLoaderRoute: typeof LearningManagementSystemInstructorAssignmentsCourseIdRouteImport
      parentRoute: typeof LearningManagementSystemInstructorRoute
    }
  }
}

interface AttendanceManagementSystemRouteChildren {
  AttendanceManagementSystemLoginRoute: typeof AttendanceManagementSystemLoginRoute
  AttendanceManagementSystemIndexRoute: typeof AttendanceManagementSystemIndexRoute
}

const AttendanceManagementSystemRouteChildren: AttendanceManagementSystemRouteChildren =
  {
    AttendanceManagementSystemLoginRoute: AttendanceManagementSystemLoginRoute,
    AttendanceManagementSystemIndexRoute: AttendanceManagementSystemIndexRoute,
  }

const AttendanceManagementSystemRouteWithChildren =
  AttendanceManagementSystemRoute._addFileChildren(
    AttendanceManagementSystemRouteChildren,
  )

interface LearningManagementSystemAdminRouteChildren {
  LearningManagementSystemAdminAnalyticsRoute: typeof LearningManagementSystemAdminAnalyticsRoute
  LearningManagementSystemAdminAttendanceLinkRoute: typeof LearningManagementSystemAdminAttendanceLinkRoute
  LearningManagementSystemAdminCouponsRoute: typeof LearningManagementSystemAdminCouponsRoute
  LearningManagementSystemAdminEnrollmentRequestsRoute: typeof LearningManagementSystemAdminEnrollmentRequestsRoute
  LearningManagementSystemAdminReviewsRoute: typeof LearningManagementSystemAdminReviewsRoute
  LearningManagementSystemAdminTrainerApplicationsRoute: typeof LearningManagementSystemAdminTrainerApplicationsRoute
  LearningManagementSystemAdminUsersRoute: typeof LearningManagementSystemAdminUsersRoute
  LearningManagementSystemAdminIndexRoute: typeof LearningManagementSystemAdminIndexRoute
}

const LearningManagementSystemAdminRouteChildren: LearningManagementSystemAdminRouteChildren =
  {
    LearningManagementSystemAdminAnalyticsRoute:
      LearningManagementSystemAdminAnalyticsRoute,
    LearningManagementSystemAdminAttendanceLinkRoute:
      LearningManagementSystemAdminAttendanceLinkRoute,
    LearningManagementSystemAdminCouponsRoute:
      LearningManagementSystemAdminCouponsRoute,
    LearningManagementSystemAdminEnrollmentRequestsRoute:
      LearningManagementSystemAdminEnrollmentRequestsRoute,
    LearningManagementSystemAdminReviewsRoute:
      LearningManagementSystemAdminReviewsRoute,
    LearningManagementSystemAdminTrainerApplicationsRoute:
      LearningManagementSystemAdminTrainerApplicationsRoute,
    LearningManagementSystemAdminUsersRoute:
      LearningManagementSystemAdminUsersRoute,
    LearningManagementSystemAdminIndexRoute:
      LearningManagementSystemAdminIndexRoute,
  }

const LearningManagementSystemAdminRouteWithChildren =
  LearningManagementSystemAdminRoute._addFileChildren(
    LearningManagementSystemAdminRouteChildren,
  )

interface LearningManagementSystemInstructorRouteChildren {
  LearningManagementSystemInstructorProfileRoute: typeof LearningManagementSystemInstructorProfileRoute
  LearningManagementSystemInstructorIndexRoute: typeof LearningManagementSystemInstructorIndexRoute
  LearningManagementSystemInstructorAssignmentsCourseIdRoute: typeof LearningManagementSystemInstructorAssignmentsCourseIdRoute
  LearningManagementSystemInstructorCoursesIdRoute: typeof LearningManagementSystemInstructorCoursesIdRoute
}

const LearningManagementSystemInstructorRouteChildren: LearningManagementSystemInstructorRouteChildren =
  {
    LearningManagementSystemInstructorProfileRoute:
      LearningManagementSystemInstructorProfileRoute,
    LearningManagementSystemInstructorIndexRoute:
      LearningManagementSystemInstructorIndexRoute,
    LearningManagementSystemInstructorAssignmentsCourseIdRoute:
      LearningManagementSystemInstructorAssignmentsCourseIdRoute,
    LearningManagementSystemInstructorCoursesIdRoute:
      LearningManagementSystemInstructorCoursesIdRoute,
  }

const LearningManagementSystemInstructorRouteWithChildren =
  LearningManagementSystemInstructorRoute._addFileChildren(
    LearningManagementSystemInstructorRouteChildren,
  )

interface LearningManagementSystemStudentRouteChildren {
  LearningManagementSystemStudentRequestsRoute: typeof LearningManagementSystemStudentRequestsRoute
  LearningManagementSystemStudentIndexRoute: typeof LearningManagementSystemStudentIndexRoute
  LearningManagementSystemStudentPlayerCourseIdRoute: typeof LearningManagementSystemStudentPlayerCourseIdRoute
  LearningManagementSystemStudentQuizCourseIdRoute: typeof LearningManagementSystemStudentQuizCourseIdRoute
}

const LearningManagementSystemStudentRouteChildren: LearningManagementSystemStudentRouteChildren =
  {
    LearningManagementSystemStudentRequestsRoute:
      LearningManagementSystemStudentRequestsRoute,
    LearningManagementSystemStudentIndexRoute:
      LearningManagementSystemStudentIndexRoute,
    LearningManagementSystemStudentPlayerCourseIdRoute:
      LearningManagementSystemStudentPlayerCourseIdRoute,
    LearningManagementSystemStudentQuizCourseIdRoute:
      LearningManagementSystemStudentQuizCourseIdRoute,
  }

const LearningManagementSystemStudentRouteWithChildren =
  LearningManagementSystemStudentRoute._addFileChildren(
    LearningManagementSystemStudentRouteChildren,
  )

interface LearningManagementSystemRouteChildren {
  LearningManagementSystemAdminRoute: typeof LearningManagementSystemAdminRouteWithChildren
  LearningManagementSystemCatalogRoute: typeof LearningManagementSystemCatalogRoute
  LearningManagementSystemForgotPasswordRoute: typeof LearningManagementSystemForgotPasswordRoute
  LearningManagementSystemInstructorRoute: typeof LearningManagementSystemInstructorRouteWithChildren
  LearningManagementSystemLoginRoute: typeof LearningManagementSystemLoginRoute
  LearningManagementSystemResetPasswordRoute: typeof LearningManagementSystemResetPasswordRoute
  LearningManagementSystemSignupRoute: typeof LearningManagementSystemSignupRoute
  LearningManagementSystemStudentRoute: typeof LearningManagementSystemStudentRouteWithChildren
  LearningManagementSystemTrainerApplyRoute: typeof LearningManagementSystemTrainerApplyRoute
  LearningManagementSystemVerifyRoute: typeof LearningManagementSystemVerifyRoute
  LearningManagementSystemIndexRoute: typeof LearningManagementSystemIndexRoute
  LearningManagementSystemCertificateIdRoute: typeof LearningManagementSystemCertificateIdRoute
  LearningManagementSystemCoursesIdRoute: typeof LearningManagementSystemCoursesIdRoute
  LearningManagementSystemInstructorsIdRoute: typeof LearningManagementSystemInstructorsIdRoute
}

const LearningManagementSystemRouteChildren: LearningManagementSystemRouteChildren =
  {
    LearningManagementSystemAdminRoute:
      LearningManagementSystemAdminRouteWithChildren,
    LearningManagementSystemCatalogRoute: LearningManagementSystemCatalogRoute,
    LearningManagementSystemForgotPasswordRoute:
      LearningManagementSystemForgotPasswordRoute,
    LearningManagementSystemInstructorRoute:
      LearningManagementSystemInstructorRouteWithChildren,
    LearningManagementSystemLoginRoute: LearningManagementSystemLoginRoute,
    LearningManagementSystemResetPasswordRoute:
      LearningManagementSystemResetPasswordRoute,
    LearningManagementSystemSignupRoute: LearningManagementSystemSignupRoute,
    LearningManagementSystemStudentRoute:
      LearningManagementSystemStudentRouteWithChildren,
    LearningManagementSystemTrainerApplyRoute:
      LearningManagementSystemTrainerApplyRoute,
    LearningManagementSystemVerifyRoute: LearningManagementSystemVerifyRoute,
    LearningManagementSystemIndexRoute: LearningManagementSystemIndexRoute,
    LearningManagementSystemCertificateIdRoute:
      LearningManagementSystemCertificateIdRoute,
    LearningManagementSystemCoursesIdRoute:
      LearningManagementSystemCoursesIdRoute,
    LearningManagementSystemInstructorsIdRoute:
      LearningManagementSystemInstructorsIdRoute,
  }

const LearningManagementSystemRouteWithChildren =
  LearningManagementSystemRoute._addFileChildren(
    LearningManagementSystemRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AttendanceManagementSystemRoute: AttendanceManagementSystemRouteWithChildren,
  ContactRoute: ContactRoute,
  EventSurveyRoute: EventSurveyRoute,
  InitiativeSurveyRoute: InitiativeSurveyRoute,
  LearningManagementSystemRoute: LearningManagementSystemRouteWithChildren,
  OneMillionInitiativeRoute: OneMillionInitiativeRoute,
  OneMillionInitiativeDonorsRoute: OneMillionInitiativeDonorsRoute,
  OneMillionInitiativeHomeRoute: OneMillionInitiativeHomeRoute,
  RegistrationRoute: RegistrationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuperAdminRoute: SuperAdminRoute,
  AdminEventSurveyRoute: AdminEventSurveyRoute,
  AdminInitiativeRoute: AdminInitiativeRoute,
  AdminInitiativeSurveyRoute: AdminInitiativeSurveyRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiChatRoute: ApiChatRoute,
  CommunitiesKeyRoute: CommunitiesKeyRoute,
  InitiativeClaimRoute: InitiativeClaimRoute,
  NewsIdRoute: NewsIdRoute,
  ResourcesAiToolsRoute: ResourcesAiToolsRoute,
  AdminIndexRoute: AdminIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
