REVOKE EXECUTE ON FUNCTION public._require_lms_admin() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_add_application_note(_application_id uuid, _body text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_assign_application_admin(_application_id uuid, _admin_user_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_get_application_cv(_application_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_get_internship_application(_application_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_internships_overview() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_list_internship_applications(_opportunity_id uuid, _q text, _status internship_application_status, _course_id uuid, _certificate_id uuid, _assigned_admin uuid, _submitted_from timestamp with time zone, _submitted_to timestamp with time zone, _sort text, _page integer, _page_size integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_list_lms_admins() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.admin_set_application_status(_application_id uuid, _to_status internship_application_status, _reason text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ams_attach_user_to_linked_course(_ams_course_id uuid, _user_id uuid, _full_name text, _email text, _phone text, _payment_status ams_payment_status) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.ams_mark_attendance_and_complete(_session_id uuid, _registrant_id uuid, _present boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.company_leads_link_contact() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_add_lead_note_tx(_lead_type text, _lead_id uuid, _body text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_attach_identity(_contact uuid, _type text, _value text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_create_company_lead_tx(payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_create_individual_lead_tx(payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_resolve_or_conflict(_email text, _phone text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_set_lead_status_tx(_lead_type text, _lead_id uuid, _status crm_lead_status) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_update_company_lead_tx(_lead_id uuid, payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_update_individual_lead_tx(_lead_id uuid, payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.crm_upsert_contact(_display_name text, _email text, _phone text, _contact_type crm_contact_type, _organization text, _metadata jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_email(queue_name text, message_id bigint) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.enqueue_email(queue_name text, payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.individual_leads_link_contact() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.link_lms_course_to_ams(_lms_course_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.list_my_internship_applications() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_courses_guard_protected_cols() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_delete_course(_course_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_instructors_generate_slug(_base text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_instructors_guard_approved() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_instructors_set_slug() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_list_courses_with_ams_link() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_process_payout(_payout_id uuid, _approve boolean) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_profile_clear_pointer(_kind lms_profile_file_kind) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_profile_finalize_file(_kind lms_profile_file_kind, _bucket text, _path text, _mime text, _size bigint, _original_filename text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_profile_get_file(_file_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_profile_get_or_init() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_profile_update(_full_name text, _biography text, _organization text, _phone text, _locale text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_recalc_course_rating() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_register_session(_session_id uuid, _device text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_reject_enrollment_request(_request_id uuid, _admin_notes text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_request_payout(_amount numeric, _method text, _notes text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_section_sync_ams_session() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_submit_quiz(_quiz_id uuid, _answers jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_sync_ams_registrant_on_enroll() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_sync_ams_registrant_on_unenroll() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_sync_course_students_count() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_sync_primary_category() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.lms_validate_session(_session_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.move_to_dlq(source_queue text, dlq_name text, message_id bigint, payload jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.read_email_batch(queue_name text, batch_size integer, vt integer) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.set_lms_answer_instructor_flag() FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.submit_internship_application(_opportunity_id uuid, _answers jsonb) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.trainer_app_transition(_application_id uuid, _to_status trainer_application_status, _note text) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.unlink_lms_course_from_ams(_ams_course_id uuid) FROM anon, PUBLIC;
REVOKE EXECUTE ON FUNCTION public.withdraw_internship_application(_application_id uuid) FROM anon, PUBLIC;